# Generated by Django 4.1.5 on 2023-02-05 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_product_describe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="tag",
            field=models.ManyToManyField(blank=True, null=True, to="accounts.tag"),
        ),
    ]
