# Generated by Django 4.1.5 on 2023-02-07 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_product_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="date_updated",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
